### ISSUE TITLE
My planar contractions currently lead to space mismatches.

### ISSUE THREAD

**Issue by Gertian** [quantumghent/PEPSKit.jl#10]
In my first commit I managed to make the relevant diagrams planar trough the introduction of braiding symbols.

The resulting code however gives a spacemismatch on the contraction :
```julia
function northwest_corner(E4, C1, E1, peps_above, peps_below=peps_above)
    @planar opt=true corner[-1 -2 -3; -4 -5 -6] := 
        E4[-1 1 2; 3] *
        C1[3; 4] *
        E1[4 5 6; -4] *
        peps_above[21; 11 10 18 17] *
        conj(peps_below[21; 13 14 15 16])*
        τ[5 7;6 8]*τ[-5 9;-6 10]*τ[8 12;9 11]*τ[7 14;12 13]*τ[15 2;16 19]*τ[19 1;17 20]*τ[20 -2;18 -3]
end
```

The stack leads to this final function :
```julia
function planarcontract!(C::AbstractTensorMap{S,N₁,N₂},
                         A::BraidingTensor{S}   , (oindA, cindA)::Index2Tuple{2,2}, 
                         B::AbstractTensorMap{S}, (cindB, oindB)::Index2Tuple{2,N₃},
                         (p1, p2)::Index2Tuple{N₁,N₂},
                         α::Number, β::Number,
                         backend::Backend...) where {S,N₁,N₂,N₃}
```
which spits out : 
ERROR: SpaceMismatch("(ℂ^1 ⊗ ℂ^1) ← ((ℂ^1)' ⊗ ℂ^1) ≠ permute(((ℂ^1)' ⊗ ℂ^1) ← (ℂ^1 ⊗ (ℂ^1)')[(2, 4), (1, 3)] * (ℂ^1 ⊗ ℂ^1 ⊗ (ℂ^1)') ← ℂ^1[(2, 3), (1, 4)], ((1, 2), (3, 4))")
Stacktrace:

I suspect that the origin of this bug is a mislabeling of my tau indices but I dont know which is the appropriate labeling.
@Jutho  ?

**Comment by Gertian** [comment]
Update : it was indeed the convention of \tau indices. 
The contractions now work but in all likeliness there are still conventions that I don't understand !

**Comment by Jutho** [comment]
Hi Gertian, what is the confusion about the tau indices? It's as always:
outgoing1 outgoing2 incoming1 incoming2

where the tau tensor maps incoming1 to outgoing2 and vice versa (whether it is braided above or below does not matter for fermions/symmetric braiding).

**Comment by Gertian** [comment]
Lets say we have two lines a, b crossing. Naively I thought that all definitions such as
tau[a1 b1; b2 a2] --> a1, b1 cross into b2 a2
and 
tau[a1 b2;b1 a2] --> a1, b2 cross into b1 a2
would both lead to a planar diagram but this is not true.

I suspect that there is some rule related to drawing the crossings that I'm not aware of that solves this ambiguity ?

**Comment by Jutho** [comment]
The correct way to think of the tau is that

![image](https://github.com/quantumghent/PEPSKit.jl/assets/4162102/542315e0-8745-44dd-a19f-c57fa84761ef)

**Comment by Gertian** [comment]
Ok that makes sense. 
So in a contraction this would be tau[a1 a2; b1 b2]

Could you however reinterpret this as a crossing from a2,b2 to b1 a1 and hence use tau[a2 b2;a1 b1] ?
